import Link from "next/link";

export default function TempoCaseStudy(){return <main className="case-study">
  <header className="site-nav shell"><Link className="wordmark" href="/">EL<span>.</span></Link><nav><Link href="/#work">Work</Link><Link href="/about">About</Link><a href="mailto:hello@evelynli.work">Contact</a></nav></header>
  <section className="case-hero shell"><Link className="back-link" href="/">← Back to work</Link><p className="case-kicker">TEMPO · PERSONAL ENERGY PLANNER</p><h1>Planning around energy,<br/><em>not just time.</em></h1><div className="case-meta"><div><span>ROLE</span><b>UI/UX Designer</b></div><div><span>FOCUS</span><b>Research, UX, Visual Design</b></div><div><span>PLATFORM</span><b>iOS</b></div><div><span>YEAR</span><b>2025</b></div></div></section>
  <section className="case-banner"><div className="case-orbit">72%</div><div className="case-phone"><span>TEMPO</span><h2>Your week has<br/>room to breathe.</h2><div className="case-days"><i/><i/><i className="high"/><i/><i/></div></div></section>
  <section className="case-block shell two-col"><p className="eyebrow">THE CHALLENGE</p><div><h2>Calendars manage time. They don’t understand energy.</h2><p>A packed schedule can feel overwhelming even when there is technically enough time for everything. Work meetings, social plans, focused tasks, and personal commitments each affect people differently—and recovery looks different for everyone.</p><p>Some people recharge through social connection, while others regain energy through solitude and personal time. Most scheduling tools treat these activities equally, leaving users to figure out for themselves when they are taking on too much or when they need time to recover.</p><p><strong>What if your calendar could understand not only when you’re available, but also how your energy changes throughout the week?</strong></p></div></section>
  <section className="tempo-research">
    <div className="shell">
      <div className="tempo-research-head"><p className="eyebrow">USER RESEARCH</p><div><h2>Understanding how busy people plan around their energy.</h2><p>I focused on busy students and working professionals aged 18–35 whose weeks combine work, study, social commitments, personal responsibilities, and downtime. The audience was defined by a shared behavior: regularly managing competing demands on their time.</p></div></div>
      <div className="tempo-audience"><span>18–35 <small>YEARS OLD</small></span><div><small>TARGET AUDIENCE</small><strong>Busy students &amp;<br/>working professionals</strong></div></div>
      <div className="tempo-research-goals">
        <article><span>01</span><h3>Planning</h3><p>How do people decide whether they have capacity for another commitment?</p></article>
        <article><span>02</span><h3>Energy</h3><p>Which activities tend to consume or restore their energy?</p></article>
        <article><span>03</span><h3>Recovery</h3><p>How do different people recover after demanding work or social activities?</p></article>
        <article><span>04</span><h3>Awareness</h3><p>When do people realize they have overcommitted themselves?</p></article>
      </div>
      <div className="tempo-method"><p className="eyebrow">RESEARCH METHOD</p><div><h3>Semi-structured interviews</h3><p>I used open-ended questions about recent weeks, scheduling decisions, moments of exhaustion, canceled plans, and recovery habits. I avoided introducing the idea of an “energy planner” early so the conversations could reveal existing behaviors before suggesting a solution.</p><div className="tempo-question-list"><p>How do you usually plan your week?</p><p>When does a day start to feel too busy?</p><p>Does free time on your calendar always feel truly available?</p><p>Which activities drain you, and which help you recharge?</p><p>When do you realize you have scheduled too much?</p></div></div></div>
      <div className="tempo-research-question"><small>CORE RESEARCH QUESTION</small><h2>How might we help people understand the relationship between commitments, energy consumption, and recovery <em>before</em> their schedule becomes overwhelming?</h2></div>
    </div>
  </section>
  <section className="case-block shell two-col"><p className="eyebrow">THE SOLUTION</p><div><h2>A calendar with a personal energy layer.</h2><p>Tempo helps people reflect on how plans affect their energy, spot draining patterns across the week, and make room to recharge in the way that works for them.</p><div className="insight-row"><span><b>01</b>See weekly pressure</span><span><b>02</b>Map personal energy</span><span><b>03</b>Protect recovery time</span></div></div></section>
  <section className="case-ending"><div className="shell"><p>CASE STUDY IN PROGRESS</p><h2>Research, testing, and final interface explorations are being documented as the product develops.</h2><Link href="/">Return home ↗</Link></div></section>
</main>}
