import Link from "next/link";

export default function TempoCaseStudy(){return <main className="case-study">
  <header className="site-nav shell"><Link className="wordmark" href="/">EL<span>.</span></Link><nav><Link href="/#work">Work</Link><Link href="/about">About</Link><a href="mailto:hello@evelynli.work">Contact</a></nav></header>
  <section className="case-hero shell"><Link className="back-link" href="/">← Back to work</Link><p className="case-kicker">TEMPO · PERSONAL ENERGY PLANNER</p><h1>Planning around energy,<br/><em>not just time.</em></h1><div className="case-meta"><div><span>ROLE</span><b>UI/UX Designer</b></div><div><span>FOCUS</span><b>Research, UX, Visual Design</b></div><div><span>PLATFORM</span><b>iOS</b></div><div><span>YEAR</span><b>2025</b></div></div></section>
  <section className="case-banner"><div className="case-orbit">72%</div><div className="case-phone"><span>TEMPO</span><h2>Your week has<br/>room to breathe.</h2><div className="case-days"><i/><i/><i className="high"/><i/><i/></div></div></section>
  <section className="case-block shell two-col"><p className="eyebrow">THE CHALLENGE</p><div><h2>A packed calendar hides how we actually recharge.</h2><p>Balancing work with everyday life can feel overwhelming when every day is full. Some people regain energy through social connection; others need time alone. The same plan can energize one person and drain another. Yet calendars only show where our time goes, leaving us to figure out the energy cost of each commitment and when we need to recover.</p></div></section>
  <section className="case-block shell two-col"><p className="eyebrow">THE SOLUTION</p><div><h2>A calendar with a personal energy layer.</h2><p>Tempo helps people reflect on how plans affect their energy, spot draining patterns across the week, and make room to recharge in the way that works for them.</p><div className="insight-row"><span><b>01</b>See weekly pressure</span><span><b>02</b>Map personal energy</span><span><b>03</b>Protect recovery time</span></div></div></section>
  <section className="case-ending"><div className="shell"><p>CASE STUDY IN PROGRESS</p><h2>Research, testing, and final interface explorations are being documented as the product develops.</h2><Link href="/">Return home ↗</Link></div></section>
</main>}
