import Link from "next/link";

export default function TempoCaseStudy(){return <main className="case-study">
  <header className="site-nav shell"><Link className="wordmark" href="/">EL<span>.</span></Link><nav><Link href="/#work">Work</Link><Link href="/about">About</Link><a href="mailto:hello@evelynli.work">Contact</a></nav></header>
  <section className="case-hero shell"><Link className="back-link" href="/">← Back to work</Link><p className="case-kicker">TEMPO · PERSONAL ENERGY PLANNER</p><h1>Planning around energy,<br/><em>not just time.</em></h1><div className="case-meta"><div><span>ROLE</span><b>UI/UX Designer</b></div><div><span>FOCUS</span><b>Research, UX, Visual Design</b></div><div><span>PLATFORM</span><b>iOS</b></div><div><span>YEAR</span><b>2025</b></div></div></section>
  <section className="case-banner"><div className="case-orbit">72%</div><div className="case-phone"><span>TEMPO</span><h2>Your week has<br/>room to breathe.</h2><div className="case-days"><i/><i/><i className="high"/><i/><i/></div></div></section>
  <section className="case-block shell two-col"><p className="eyebrow">THE CHALLENGE</p><div><h2>Free time doesn’t always mean available energy.</h2><p>Traditional calendars show whether a time slot is open. They rarely help people understand whether another meeting, trip, or social commitment will leave them overwhelmed.</p></div></section>
  <section className="case-block shell two-col"><p className="eyebrow">THE SOLUTION</p><div><h2>A calendar with an energy layer.</h2><p>Tempo lets people assign an energy cost to plans, recognize overloaded days, and reserve recovery time before committing.</p><div className="insight-row"><span><b>01</b>See weekly pressure</span><span><b>02</b>Estimate energy cost</span><span><b>03</b>Protect recovery time</span></div></div></section>
  <section className="case-ending"><div className="shell"><p>CASE STUDY IN PROGRESS</p><h2>Research, testing, and final interface explorations are being documented as the product develops.</h2><Link href="/">Return home ↗</Link></div></section>
</main>}
