import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Shiftline — Evelyn Li",
  description: "A concept case study for a restaurant operations platform that brings scheduling, break coverage, and tip allocation into one clear workflow.",
};

export default function ShiftlineCaseStudy() {
  return <main className="shiftline-case">
    <header className="site-nav shell"><Link className="wordmark" href="/" aria-label="Evelyn Li home">EL<span>.</span></Link><nav aria-label="Main navigation"><Link href="/#work">Work</Link><Link href="/about">About</Link><a href="mailto:hello@evelynli.work">Contact</a></nav></header>
    <section className="case-hero shell"><Link className="back-link" href="/#work">← Back to work</Link><p className="case-kicker">SHIFTLINE · RESTAURANT OPERATIONS CONCEPT</p><h1>One shift.<br/><em>A clearer picture.</em></h1><div className="case-meta"><div><span>ROLE</span><b>UI/UX Designer</b></div><div><span>FOCUS</span><b>Workflow UX, Product Strategy</b></div><div><span>PLATFORM</span><b>Desktop SaaS Concept</b></div><div><span>STATUS</span><b>Concept · 2026</b></div></div></section>
    <section className="shiftline-case-banner" aria-label="Shiftline dashboard concept preview"><div className="shiftline-case-screen"><div className="shiftline-top"><span className="shiftline-brand"><i/> shiftline</span><span>MANAGER WORKSPACE <b>↗</b></span></div><div className="shiftline-case-ui"><div><small>WEEKLY OPERATIONS</small><h2>See the whole shift.</h2><p>Tuesday, September 29</p><div className="shiftline-case-bars"><span>Kitchen <i/></span><span>Service <i/></span><span>Breaks <i/></span></div></div><aside><small>ATTENTION NEEDED</small><strong>2 coverage conflicts</strong><p>Review overlapping breaks before publishing.</p><span>Review schedule ↗</span></aside></div></div></section>
    <section className="case-block shell"><p className="eyebrow">THE CHALLENGE</p><div><h2>Restaurant operations are managed across too many disconnected tools.</h2><p>Restaurant managers often coordinate schedules, employee availability, break compliance, attendance, shift changes, and tip distribution across spreadsheets, group chats, time clocks, and POS systems.</p><p>Each tool solves one part of the workflow, but managers are left to connect the information manually. A small scheduling change can affect station coverage, labor hours, breaks, and payroll—turning routine shift management into a constant coordination problem.</p><p><strong>How might we give managers one operational view of the shift, so they can catch conflicts before they become service problems?</strong></p><p className="shiftline-note">This is an independent concept study informed by restaurant operations experience. It has not been launched or evaluated with formal user testing.</p></div></section>
    <section className="case-block shell"><p className="eyebrow">THE DESIGN QUESTION</p><div><h2>How can a manager spot the next problem before publishing the shift?</h2><p>Shiftline brings related decisions into one workspace. A manager can draft a schedule, inspect break coverage, and preview a tip split without losing context between steps.</p><div className="insight-row"><span><b>01</b>Draft shifts by role</span><span><b>02</b>Check break coverage</span><span><b>03</b>Preview tip allocation</span></div></div></section>
    <section className="shiftline-process"><div className="shell"><p className="eyebrow">CORE WORKFLOW</p><h2>From draft to confident handoff.</h2><div className="shiftline-process-grid"><article><span>01 / PLAN</span><h3>Build the schedule</h3><p>See staff by role and time. Gaps remain visible while assignments are still being adjusted.</p></article><article><span>02 / REVIEW</span><h3>Protect coverage</h3><p>Spot overlapping breaks and revisit the affected station before the schedule goes out.</p></article><article><span>03 / PREVIEW</span><h3>Explain the split</h3><p>Preview how the manager's tip rules apply to recorded shifts before finalizing a payout.</p></article></div></div></section>
    <section className="case-block shell"><p className="eyebrow">PRODUCT THINKING</p><div><h2>Designed for daily use. Structured for a subscription product.</h2><p>The starting point is a single-location manager workflow. Team access, reusable role templates, and a shift history could form the foundation for a multi-location SaaS product. This business model is a direction for the concept, not a validated outcome.</p></div></section>
    <section className="case-ending"><div className="shell"><p>CONCEPT IN DEVELOPMENT</p><h2>Next: prototype the schedule review flow and test whether managers can resolve coverage conflicts quickly.</h2><Link href="/#work">Back to selected work ↗</Link></div></section>
  </main>;
}
