import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Trace — Evelyn Li",
  description: "Trace is a B2B SaaS concept for AI companies to compare model releases, review failures, and make shared launch decisions.",
};

export default function TraceCaseStudy() {
  return <main className="trace-case">
    <header className="site-nav shell"><Link className="wordmark" href="/" aria-label="Evelyn Li home">EL<span>.</span></Link><nav aria-label="Main navigation"><Link href="/#work">Work</Link><Link href="/about">About</Link><a href="mailto:hello@evelynli.work">Contact</a></nav></header>
    <section className="case-hero shell"><Link className="back-link" href="/#work">← Back to work</Link><p className="case-kicker">TRACE · AI RELEASE REVIEW PLATFORM</p><h1>Ship AI with<br/><em>eyes open.</em></h1><div className="case-meta"><div><span>ROLE</span><b>UI/UX Designer</b></div><div><span>PRODUCT</span><b>B2B SaaS Concept</b></div><div><span>USERS</span><b>AI Product Teams</b></div><div><span>STATUS</span><b>Concept · 2026</b></div></div></section>
    <section className="trace-case-banner" aria-label="Trace release review interface concept"><div className="trace-window"><div className="trace-window-top"><span className="trace-logo">◈ &nbsp; trace</span><span>ORBIT AI / RELEASES</span><span>● &nbsp; REVIEW OPEN</span></div><div className="trace-window-body"><div className="trace-window-main"><small>DEMO DATA · RELEASE REVIEW</small><h2>Assistant v2.4 <span>→</span> v2.5</h2><p>A single place to review what improved and what needs attention before launch.</p><div className="trace-metrics"><div><small>ANSWER QUALITY</small><strong>Improved ↗</strong></div><div><small>LATENCY</small><strong>Stable →</strong></div><div><small>COST PER RESPONSE</small><strong>Higher ↗</strong></div></div><div className="trace-example"><span>FLAGGED EXAMPLE</span><strong>Answer missed a policy exception</strong><p>Review the source, compare both answers, and assign a decision owner.</p></div></div><aside><small>RELEASE CHECKLIST</small><p>✓ Evaluation run complete</p><p>✓ Product review complete</p><p>○ Cost review pending</p><p>○ Final approval pending</p><b>Hold for review</b></aside></div></div></section>
    <section className="case-block shell"><p className="eyebrow">THE OPPORTUNITY</p><div><h2>A better answer in one test can hide a worse experience elsewhere.</h2><p>AI companies compare models across answer quality, speed, and cost. Results often live in separate reports, while examples that need human judgment get passed around in threads. Trace brings the release decision into a shared workspace where evidence and ownership stay together.</p><p className="trace-disclosure">Independent product concept. The interface uses illustrative demo data; no customer research or production results are claimed.</p></div></section>
    <section className="case-block shell"><p className="eyebrow">THE WORKFLOW</p><div><h2>From evaluation run to release decision.</h2><p>Teams select a baseline and candidate version, inspect changes by category, review flagged responses, then record a decision with the people responsible for launch.</p><div className="insight-row"><span><b>01</b>Compare versions</span><span><b>02</b>Review failures</span><span><b>03</b>Approve or hold</span></div></div></section>
    <section className="trace-roles"><div className="shell"><p className="eyebrow">DESIGNED FOR TEAMS</p><h2>Different roles. One release record.</h2><div className="trace-roles-grid"><article><span>PRODUCT</span><h3>What changed?</h3><p>See the tradeoffs that affect users and the launch recommendation.</p></article><article><span>ENGINEERING</span><h3>Where did it fail?</h3><p>Open examples with evaluation context and track follow-up work.</p></article><article><span>REVIEWER</span><h3>Who approved it?</h3><p>Give a decision with a reason, time, and visible ownership.</p></article></div></div></section>
    <section className="case-block shell"><p className="eyebrow">THE SAAS MODEL</p><div><h2>Built around the AI company's ongoing release cycle.</h2><p>Each company gets its own workspace with version history, team roles, and review permissions. A subscription could cover seats and a monthly evaluation allowance, with usage tiers for larger teams. The pricing structure is a product hypothesis for this concept.</p></div></section>
    <section className="case-ending"><div className="shell"><p>CONCEPT IN DEVELOPMENT</p><h2>Next: prototype the flagged-example review and test whether teams can make a release decision from the same evidence.</h2><Link href="/#work">Back to selected work ↗</Link></div></section>
  </main>;
}
